# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: (^docs/_vendor/|.*pb2.*)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^(deployments/helm-chart.*/templates|deployments/helm-chart/crds)
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-vcs-permalinks
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: ^(tests/suite/utils|tests/suite/fixtures|tests/suite/grpc|tests/settings.py)
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: fix-byte-order-marker
      - id: detect-private-key
        exclude: ^(examples/|tests/|internal/k8s/secrets/)

  - repo: local
    hooks:
      - id: golang-diff
        name: create-go-diff
        entry: bash -c 'git diff -p origin/main > /tmp/diff.patch'
        language: system
        types: [go]
        pass_filenames: false

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.54.2
    hooks:
      - id: golangci-lint
        args: [--new-from-patch=/tmp/diff.patch]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.11.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - id: check-jsonschema
        name: "Check Helm Chart JSON Schema"
        files: deployments/helm-chart/values.yaml
        types: [yaml]
        args: ['--schemafile', 'deployments/helm-chart/values.schema.json']

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.10.0
    hooks:
    - id: markdownlint-cli2

ci:
  skip: [golang-diff, golangci-lint, check-jsonschema, markdownlint-cli2]
