[tool.black]
line-length = 120
target-version = ['py310']
extend-exclude = '.*pb2.*'

[tool.isort]
atomic = true
profile = "black"
line_length = 120
skip_gitignore = true
balanced_wrapping = true
filter_files = true
skip_glob = ['*pb2*']

[tool.pytest.ini_options]
pythonpath = [
    ".",
    "tests/suite",
    "tests/suite/grpc",
    "tests/suite/fixtures",
    "tests/suite/utils",
]
addopts = "--tb=native -ra --disable-warnings -x -l -v --strict-markers"
log_cli = true
markers =[
    "agent",
    "annotations",
    "appprotect",
    "appprotect_integration",
    "appprotect_waf_policies",
    "appprotect_waf_policies_allow",
    "appprotect_waf_policies_block",
    "appprotect_waf_policies_grpc",
    "appprotect_waf_policies_vsr",
    "appprotect_waf_v5",
    "appprotect_watch",
    "appprotect_batch",
    "basic_auth",
    "batch_start",
    "create",
    "delete",
    "dos",
    "dos_ingress",
    "dos_learning",
    "hsts",
    "ingresses",
    "multi_ns",
    "policies",
    "policies_rl",
    "policies_jwt",
    "policies_ac",
    "policies_mtls",
    "rewrite",
    "skip_for_nginx_oss",
    "skip_for_loadbalancer",
    "smoke",
    "startup",
    "ts",
    "upgrade",
    "vs",
    "vs_api",
    "vs_backup",
    "vs_ipv6",
    "vs_rewrite",
    "vs_responses",
    "vs_grpc",
    "vs_redirects",
    "vs_externaldns",
    "vs_externalname",
    "vs_canary",
    "vs_certmanager",
    "vs_config_map",
    "vs_grpc",
    "vs_upstream",
    "vs_use_cluster_ip",
    "vsr",
    "vsr_api",
    "vsr_basic",
    "vsr_canned",
    "vsr_canary",
    "vsr_error_pages",
    "vsr_external_name",
    "vsr_grpc",
    "vsr_redirects",
    "vsr_regexes",
    "vsr_rewrite",
    "vsr_routing",
    "vsr_secrets",
    "vsr_splits",
    "vsr_status",
    "vsr_upstream",
    "watch_namespace",
    "wildcard_tls",
]
testpaths = [
    "tests",
    "perf-tests",
]
