apiVersion: v2
name: nginx-ingress
version: 1.3.1
appVersion: 3.6.1
kubeVersion: ">= 1.23.0-0"
type: application
description: NGINX Ingress Controller
icon: https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v3.6.1/charts/nginx-ingress/chart-icon.png
home: https://github.com/nginxinc/kubernetes-ingress
sources:
  - https://github.com/nginxinc/kubernetes-ingress/tree/v3.6.1/charts/nginx-ingress
keywords:
  - ingress
  - nginx
maintainers:
  - name: nginxinc
    email: kubernetes@nginx.com
