name: "Release NGINX Ingress Controller OSS Images"

on:
  workflow_dispatch:
    inputs:
      gcr_release_registry:
        required: true
        type: boolean
      ecr_public_registry:
        required: true
        type: boolean
      dockerhub_public_registry:
        required: true
        type: boolean
      quay_public_registry:
        required: true
        type: boolean
      github_public_registry:
        required: true
        type: boolean
      source_tag:
        required: true
        type: string
      target_tag:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: "main"
      dry_run:
        type: boolean
        default: false
  workflow_call:
    inputs:
      gcr_release_registry:
        required: true
        type: boolean
      ecr_public_registry:
        required: true
        type: boolean
      dockerhub_public_registry:
        required: true
        type: boolean
      quay_public_registry:
        required: true
        type: boolean
      github_public_registry:
        required: true
        type: boolean
      source_tag:
        required: true
        type: string
      target_tag:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: "main"
      dry_run:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  release-to-gcr-release-registry:
    name: Push images to the GCR Release Registry
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    if: ${{ inputs.gcr_release_registry }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.branch }}

      - name: Azure login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.AZURE_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_VAULT_SUBSCRIPTION_ID }}

      - name: Setup secrets
        id: secrets
        run: |
          echo "Setting secrets for job"
          GCR_WORKLOAD_ID=$(az keyvault secret show --name gcr-workload-identity --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_WORKLOAD_ID"
          echo "GCR_WORKLOAD_ID=$GCR_WORKLOAD_ID" >> $GITHUB_OUTPUT
          GCR_SERVICE_ACCOUNT=$(az keyvault secret show --name kic-pipeline-gcr-sa --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_SERVICE_ACCOUNT"
          echo "GCR_SERVICE_ACCOUNT=$GCR_SERVICE_ACCOUNT" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        id: gcr-auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          token_format: access_token
          workload_identity_provider: ${{ steps.secrets.outputs.GCR_WORKLOAD_ID }}
          service_account: ${{ steps.secrets.outputs.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.gcr-auth.outputs.access_token }}

      - name: Publish OSS images
        run: |
          export CONFIG_PATH=.github/config/config-oss-gcr-release
          export SOURCE_TAG=${{ inputs.source_tag }}
          export TARGET_TAG=${{ inputs.target_tag }}
          if ${{ inputs.dry_run }}; then
            export DRY_RUN=true
          fi
          .github/scripts/copy-images.sh

  release-oss-to-ecr-public-registry:
    name: Push OSS images to the AWS Public Registry
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    if: ${{ inputs.ecr_public_registry }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.branch }}

      - name: Azure login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.AZURE_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_VAULT_SUBSCRIPTION_ID }}

      - name: Setup secrets
        id: secrets
        run: |
          echo "Setting secrets for job"
          GCR_WORKLOAD_ID=$(az keyvault secret show --name gcr-workload-identity --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_WORKLOAD_ID"
          echo "GCR_WORKLOAD_ID=$GCR_WORKLOAD_ID" >> $GITHUB_OUTPUT
          GCR_SERVICE_ACCOUNT=$(az keyvault secret show --name kic-pipeline-gcr-sa --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_SERVICE_ACCOUNT"
          echo "GCR_SERVICE_ACCOUNT=$GCR_SERVICE_ACCOUNT" >> $GITHUB_OUTPUT
          AWS_ROLE_PUBLIC_ECR=$(az keyvault secret show --name aws-public-role --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$AWS_ROLE_PUBLIC_ECR"
          echo "AWS_ROLE_PUBLIC_ECR=$AWS_ROLE_PUBLIC_ECR" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        id: gcr-auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          token_format: access_token
          workload_identity_provider: ${{ steps.secrets.outputs.GCR_WORKLOAD_ID }}
          service_account: ${{ steps.secrets.outputs.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.gcr-auth.outputs.access_token }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ steps.secrets.outputs.AWS_ROLE_PUBLIC_ECR }}

      - name: Login to Public ECR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: public.ecr.aws

      - name: Publish images
        run: |
          export CONFIG_PATH=.github/config/config-oss-ecr
          export SOURCE_TAG=${{ inputs.source_tag }}
          export TARGET_TAG=${{ inputs.target_tag }}
          if ${{ inputs.dry_run }}; then
            export DRY_RUN=true
          fi
          .github/scripts/copy-images.sh

  release-oss-to-dockerhub-public-registry:
    name: Push OSS images to the DockerHub Public Registry
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    if: ${{ inputs.dockerhub_public_registry }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.branch }}

      - name: Azure login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.AZURE_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_VAULT_SUBSCRIPTION_ID }}

      - name: Setup secrets
        id: secrets
        run: |
          echo "Setting secrets for job"
          GCR_WORKLOAD_ID=$(az keyvault secret show --name gcr-workload-identity --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_WORKLOAD_ID"
          echo "GCR_WORKLOAD_ID=$GCR_WORKLOAD_ID" >> $GITHUB_OUTPUT
          GCR_SERVICE_ACCOUNT=$(az keyvault secret show --name kic-pipeline-gcr-sa --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_SERVICE_ACCOUNT"
          echo "GCR_SERVICE_ACCOUNT=$GCR_SERVICE_ACCOUNT" >> $GITHUB_OUTPUT

      - name: Azure login Common Vault
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.AZURE_COMMON_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_COMMON_VAULT_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_COMMON_VAULT_SUBSCRIPTION_ID }}

      - name: Setup secrets Common Vault
        id: secrets-common
        run: |
          echo "Setting secrets for job"
          DOCKER_USERNAME=$(az keyvault secret show --name docker-username --vault-name ${{ secrets.COMMON_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$DOCKER_USERNAME"
          echo "DOCKER_USERNAME=$DOCKER_USERNAME" >> $GITHUB_OUTPUT
          DOCKER_PASSWORD=$(az keyvault secret show --name docker-password --vault-name ${{ secrets.COMMON_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$DOCKER_PASSWORD"
          echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        id: gcr-auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          token_format: access_token
          workload_identity_provider: ${{ steps.secrets.outputs.GCR_WORKLOAD_ID }}
          service_account: ${{ steps.secrets.outputs.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.gcr-auth.outputs.access_token }}

      - name: DockerHub Login
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ steps.secrets-common.outputs.DOCKER_USERNAME }}
          password: ${{ steps.secrets-common.outputs.DOCKER_PASSWORD }}

      - name: Publish images
        run: |
          export CONFIG_PATH=.github/config/config-oss-dockerhub
          export SOURCE_TAG=${{ inputs.source_tag }}
          export TARGET_TAG=${{ inputs.target_tag }}
          if ${{ inputs.dry_run }}; then
            export DRY_RUN=true
          fi
          .github/scripts/copy-images.sh

  release-oss-to-quay-public-registry:
    name: Push OSS images to the Quay Public Registry
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    if: ${{ inputs.quay_public_registry }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.branch }}

      - name: Azure login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.AZURE_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_VAULT_SUBSCRIPTION_ID }}

      - name: Setup secrets
        id: secrets
        run: |
          echo "Setting secrets for job"
          GCR_WORKLOAD_ID=$(az keyvault secret show --name gcr-workload-identity --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_WORKLOAD_ID"
          echo "GCR_WORKLOAD_ID=$GCR_WORKLOAD_ID" >> $GITHUB_OUTPUT
          GCR_SERVICE_ACCOUNT=$(az keyvault secret show --name kic-pipeline-gcr-sa --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_SERVICE_ACCOUNT"
          echo "GCR_SERVICE_ACCOUNT=$GCR_SERVICE_ACCOUNT" >> $GITHUB_OUTPUT
          QUAY_CREDS=$(az keyvault secret show --name quay-creds --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$QUAY_CREDS"
          QUAY_USERNAME=$(echo $QUAY_CREDS | jq -r '.username')
          echo "::add-mask::$QUAY_USERNAME"
          echo "QUAY_USERNAME=$QUAY_USERNAME" >> $GITHUB_OUTPUT
          QUAY_ROBOT_TOKEN=$(echo $QUAY_CREDS | jq -r '.token')
          echo "::add-mask::$QUAY_ROBOT_TOKEN"
          echo "QUAY_ROBOT_TOKEN=$QUAY_ROBOT_TOKEN" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        id: gcr-auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          token_format: access_token
          workload_identity_provider: ${{ steps.secrets.outputs.GCR_WORKLOAD_ID }}
          service_account: ${{ steps.secrets.outputs.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.gcr-auth.outputs.access_token }}

      - name: Login to Quay.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ steps.secrets.outputs.QUAY_USERNAME }}
          password: ${{ steps.secrets.outputs.QUAY_ROBOT_TOKEN }}

      - name: Publish images
        run: |
          export CONFIG_PATH=.github/config/config-oss-quay
          export SOURCE_TAG=${{ inputs.source_tag }}
          export TARGET_TAG=${{ inputs.target_tag }}
          if ${{ inputs.dry_run }}; then
            export DRY_RUN=true
          fi
          .github/scripts/copy-images.sh

  release-oss-to-github-public-registry:
    name: Push OSS images to the GitHub Public Registry
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
      packages: write
    if: ${{ inputs.github_public_registry }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.branch }}

      - name: Azure login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.AZURE_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_VAULT_SUBSCRIPTION_ID }}

      - name: Setup secrets
        id: secrets
        run: |
          echo "Setting secrets for job"
          GCR_WORKLOAD_ID=$(az keyvault secret show --name gcr-workload-identity --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_WORKLOAD_ID"
          echo "GCR_WORKLOAD_ID=$GCR_WORKLOAD_ID" >> $GITHUB_OUTPUT
          GCR_SERVICE_ACCOUNT=$(az keyvault secret show --name kic-pipeline-gcr-sa --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_SERVICE_ACCOUNT"
          echo "GCR_SERVICE_ACCOUNT=$GCR_SERVICE_ACCOUNT" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        id: gcr-auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          token_format: access_token
          workload_identity_provider: ${{ steps.secrets.outputs.GCR_WORKLOAD_ID }}
          service_account: ${{ steps.secrets.outputs.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.gcr-auth.outputs.access_token }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish images
        run: |
          export CONFIG_PATH=.github/config/config-oss-github
          export SOURCE_TAG=${{ inputs.source_tag }}
          export TARGET_TAG=${{ inputs.target_tag }}
          if ${{ inputs.dry_run }}; then
            export DRY_RUN=true
          fi
          .github/scripts/copy-images.sh
