name: Setup Smoke tests

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      target:
        required: true
        type: string
      nap-modules:
        required: true
        type: string
      marker:
        required: true
        type: string
      label:
        required: true
        type: string
      go-md5:
        required: true
        type: string
      build-tag:
        required: true
        type: string
      stable-tag:
        required: true
        type: string
      authenticated:
        required: true
        type: boolean
      k8s-version:
        required: true
        type: string
      force:
        required: true
        type: boolean

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  setup-smoke:
    permissions:
      contents: read # for docker/build-push-action to read repo content
      id-token: write # for OIDC login to GCR
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set image variables
        id: image_details
        run: |
          echo "name=gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/nginx-ic${{ contains(inputs.nap-modules, 'dos') && '-dos' || '' }}${{ contains(inputs.nap-modules, 'waf') && '-nap' || '' }}${{ contains(inputs.image, 'v5') && '-v5' || '' }}/nginx${{ contains(inputs.image, 'plus') && '-plus' || '' }}-ingress" >> $GITHUB_OUTPUT
          echo "build_tag=${{ inputs.build-tag }}${{ contains(inputs.image, 'ubi-9') && '-ubi' || '' }}${{ contains(inputs.image, 'ubi-8') && '-ubi8' || '' }}${{ contains(inputs.image, 'alpine') && '-alpine' || '' }}${{ contains(inputs.target, 'aws') && '-mktpl' || '' }}${{ contains(inputs.image, 'fips') && '-fips' || ''}}" >> $GITHUB_OUTPUT
          echo "stable_tag=${{ inputs.stable-tag }}${{ contains(inputs.image, 'ubi-9') && '-ubi' || '' }}${{ contains(inputs.image, 'ubi-8') && '-ubi8' || '' }}${{ contains(inputs.image, 'alpine') && '-alpine' || '' }}${{ contains(inputs.target, 'aws') && '-mktpl' || '' }}${{ contains(inputs.image, 'fips') && '-fips' || ''}}" >> $GITHUB_OUTPUT

      - name: Azure login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.AZURE_VAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_VAULT_SUBSCRIPTION_ID }}
        if: ${{ inputs.authenticated }}

      - name: Setup secrets
        id: secrets
        run: |
          echo "Setting secrets for job"
          GCR_WORKLOAD_ID=$(az keyvault secret show --name gcr-workload-identity --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_WORKLOAD_ID"
          echo "GCR_WORKLOAD_ID=$GCR_WORKLOAD_ID" >> $GITHUB_OUTPUT
          GCR_SERVICE_ACCOUNT=$(az keyvault secret show --name kic-pipeline-gcr-sa --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$GCR_SERVICE_ACCOUNT"
          echo "GCR_SERVICE_ACCOUNT=$GCR_SERVICE_ACCOUNT" >> $GITHUB_OUTPUT
          PLUS_CREDS=$(az keyvault secret show --name plus-creds --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$PLUS_CREDS"
          PLUS_JWT=$(echo $PLUS_CREDS | jq -r '.jwt')
          echo "::add-mask::$PLUS_JWT"
          echo "PLUS_JWT=$PLUS_JWT" >> $GITHUB_OUTPUT
          IFS=@ CERT=$(echo $PLUS_CREDS | jq -r '.crt')
          while read -r line; do
            echo "::add-mask::${line}"
          done <<< "${CERT}"
          echo $CERT > nginx-repo.crt
          IFS=@ KEY=$(echo $PLUS_CREDS | jq -r '.key')
          while read -r line; do
            echo "::add-mask::${line}"
          done <<< "${KEY}"
          echo $KEY > nginx-repo.key
          IFS=@ RHEL_CREDS=$(az keyvault secret show --name rhel-creds --vault-name ${{ secrets.NIC_KEYVAULT_NAME }} --query value -o tsv)
          while read -r line; do
            echo "::add-mask::${line}"
          done <<< "${RHEL_CREDS}"
          echo $RHEL_CREDS > rhel_license
        if: ${{ inputs.authenticated }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          token_format: access_token
          workload_identity_provider: ${{ steps.secrets.outputs.GCR_WORKLOAD_ID }}
          service_account: ${{ steps.secrets.outputs.GCR_SERVICE_ACCOUNT }}
        if: ${{ inputs.authenticated }}

      - name: Login to GCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
        if: ${{ inputs.authenticated }}

      - name: Check if stable image exists
        id: stable_exists
        run: |
          if docker pull ${{ steps.image_details.outputs.name }}:${{ steps.image_details.outputs.stable_tag }}; then
            echo "exists=true" >> $GITHUB_OUTPUT
          fi
          if [ "${{ inputs.force }}" = "true" ]; then
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        if: ${{ inputs.authenticated }}

      - name: NAP modules
        id: nap_modules
        run: |
          [[ "${{ inputs.nap-modules }}" == "waf,dos" ]] && modules="waf-dos" || modules="${{ inputs.nap-modules }}"
          echo "modules=${modules}" >> $GITHUB_OUTPUT
        if: ${{ inputs.nap-modules }}

      - name: Pull build image
        run: |
          docker pull ${{ steps.image_details.outputs.name }}:${{ steps.image_details.outputs.build_tag }}
        if: ${{ inputs.authenticated && steps.stable_exists.outputs.exists != 'true'  }}

      - name: Fetch Cached Artifacts
        uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ${{ github.workspace }}/dist
          key: nginx-ingress-${{ inputs.go-md5 }}
          fail-on-cache-miss: true
        if: ${{ !inputs.authenticated }}

      - name: Check if pytest image exists
        id: check-image
        run: |
          docker manifest inspect "gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/test-runner:${{ hashFiles('./tests/requirements.txt', './tests/Dockerfile') || 'latest' }}"
        shell: bash
        continue-on-error: true
        if: ${{ inputs.authenticated  }}

      - name: Build Pytest-Runner Container
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: tests/Dockerfile
          context: "."
          cache-from: type=gha,scope=test-runner
          tags: "gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/test-runner:${{ hashFiles('./tests/requirements.txt', './tests/Dockerfile') || 'latest' }}"
          pull: true
          push: ${{ inputs.authenticated }}
          load: ${{ !inputs.authenticated }}
        if: ${{ ( !inputs.authenticated || steps.check-image.outcome == 'failure' )  }}

      - name: Build ${{ inputs.image }} Container
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: build/Dockerfile
          context: "."
          cache-from: type=gha,scope=${{ inputs.image }}${{ steps.nap_modules.outputs.name != '' && format('-{0}', steps.nap_modules.outputs.name) || '' }}
          target: goreleaser
          tags: "${{ steps.image_details.outputs.name }}:${{ steps.image_details.outputs.build_tag }}"
          load: true
          pull: true
          build-args: |
            BUILD_OS=${{ inputs.image }}
            IC_VERSION=CI
            ${{ contains(inputs.image, 'nap') && format('NAP_MODULES={0}', steps.nap_modules.outputs.modules) || '' }}
            ${{ contains(inputs.marker, 'appprotect') && 'DEBIAN_VERSION=buster-slim' || '' }}
          secret-files: |
            nginx-repo.crt=nginx-repo.crt
            nginx-repo.key=nginx-repo.key
            ${{ contains(inputs.image, 'ubi') && 'rhel_license=rhel_license' || '' }}
        if: ${{ !inputs.authenticated }}

      - name: Generate WAF v5 tgz from JSON
        run: |
          docker run --rm --user root -v /var/run/docker.sock:/var/run/docker.sock -v ${{ github.workspace }}/tests/data/ap-waf-v5:/data gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/nap/waf-compiler:5.10.0 -p /data/wafv5.json -o /data/wafv5.tgz
        if: ${{ contains(inputs.image, 'nap-v5')}}

      - name: Run Smoke Tests
        id: smoke-tests
        uses: ./.github/actions/smoke-tests
        with:
          image-type: ${{ inputs.image }}
          image-name: ${{ steps.image_details.outputs.name }}
          tag: ${{ steps.image_details.outputs.build_tag }}
          marker: ${{ inputs.marker != '' && inputs.marker || '' }}
          label: ${{ inputs.label }}
          k8s-version: ${{ inputs.k8s-version }}
          registry-token: ${{ steps.auth.outputs.access_token }}
          test-image: "gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/test-runner:${{ hashFiles('./tests/requirements.txt', './tests/Dockerfile') || 'latest' }}"
          plus-jwt: ${{ steps.secrets.outputs.PLUS_JWT }}
        if: ${{ steps.stable_exists.outputs.exists != 'true'  }}

      - name: Upload Test Results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ steps.smoke-tests.outputs.test-results-name }}
          path: ${{ steps.smoke-tests.outputs.test-results-path }}
        if: ${{ !cancelled() && steps.stable_exists.outputs.exists != 'true' }}

      - name: Clean up secrets
        run: |
          rm -f nginx-repo.crt nginx-repo.key rhel_license
        if: always()
