name: Run python tests on single image
run-name: Testing ${{ inputs.image }}:${{ inputs.tag }} on ${{ inputs.k8s-version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      image:
        type: string
        description: "Image to test"
        required: true
      tag:
        type: string
        description: "Image tag to test"
        required: true
      k8s-version:
        type: string
        description: "k8s version to test with, e.g. 1.30.0"
        required: true
      type:
        type: string
        description: "oss or plus"
        required: false
        default: oss
      marker:
        type: string
        description: "pytest markers to apply"
        required: false
        default: "'not upgrade'"
      test-image-tag:
        type: string
        description: "The tag for the test image"
        required: false
        default: latest
  workflow_call:
    inputs:
      image:
        type: string
        description: "Image to test"
        required: true
      tag:
        type: string
        description: "Image tag to test"
        required: true
      k8s-version:
        type: string
        description: "e.g. 1.30.0"
        required: true
      type:
        type: string
        description: "oss or plus"
        required: false
        default: oss
      marker:
        type: string
        description: "pytest markers to apply"
        required: false
        default: "'not upgrade'"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-single-run
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  checks:
    name: Run regression
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCR_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Pull image to local docker engine
        run: |
          docker pull ${{ inputs.image }}:${{ inputs.tag }}

      - name: Run Tests
        uses: ./.github/actions/smoke-tests
        with:
          image-type: ${{ inputs.type }}
          image-name: ${{ inputs.image }}
          tag: ${{ inputs.tag }}
          marker: ${{ inputs.marker }}
          label: "${{ inputs.image }} regression"
          k8s-version: ${{ inputs.k8s-version }}
          azure-ad-secret: ${{ secrets.AZURE_AD_AUTOMATION }}
          registry-token: ${{ steps.auth.outputs.access_token }}
          test-image: "gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/test-runner:${{ inputs.test-image-tag }}"
          plus-jwt: ${{ secrets.PLUS_JWT }}
