name: Run python tests on single image
run-name: Testing ${{ inputs.image }}:${{ inputs.tag }} on ${{ inputs.k8s-version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      image:
        type: string
        description: "Image to test"
        required: true
      tag:
        type: string
        description: "Image tag to test"
        required: true
      k8s-version:
        type: string
        description: "k8s version to test with, e.g. 1.30.0"
        required: true
      type:
        type: string
        description: "oss or plus"
        required: false
        default: oss
      marker:
        type: string
        description: "pytest markers to apply"
        required: false
        default: "'not upgrade'"
  workflow_call:
    inputs:
      image:
        type: string
        description: "Image to test"
        required: true
      tag:
        type: string
        description: "Image tag to test"
        required: true
      k8s-version:
        type: string
        description: "e.g. 1.30.0"
        required: true
      type:
        type: string
        description: "oss or plus"
        required: false
        default: oss
      marker:
        type: string
        description: "pytest markers to apply"
        required: false
        default: "'not upgrade'"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-single-run
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  checks:
    name: Run regression
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCR_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Pull image to local docker engine
        run: |
          docker pull ${{ inputs.image }}:${{ inputs.tag }}

      - name: Check if test image exists
        id: check-image
        run: |
          docker manifest inspect "gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/test-runner:${{ hashFiles('./tests/requirements.txt', './tests/Dockerfile') }}"
        shell: bash
        continue-on-error: true

      - name: Build Test-Runner Container
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: tests/Dockerfile
          context: "."
          cache-from: type=gha,scope=test-runner
          tags: "gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/test-runner:${{ hashFiles('./tests/requirements.txt', './tests/Dockerfile') }}"
          pull: true
          push: false
          load: true
        if: ${{ steps.check-image.outcome == 'failure' }}

      - name: Run Tests
        uses: ./.github/actions/smoke-tests
        with:
          image-type: ${{ inputs.type }}
          image-name: ${{ inputs.image }}
          tag: ${{ inputs.tag }}
          marker: ${{ inputs.marker }}
          label: "${{ inputs.image }} regression"
          k8s-version: ${{ inputs.k8s-version }}
          azure-ad-secret: ${{ secrets.AZURE_AD_AUTOMATION }}
          registry-token: ${{ steps.auth.outputs.access_token }}
          test-image: "gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/test-runner:${{ hashFiles('./tests/requirements.txt', './tests/Dockerfile') }}"
          plus-jwt: ${{ secrets.PLUS_JWT }}
