name: Sync

on:
  workflow_run:
    branches: master
    workflows:
      - "Continuous Integration"
    types:
      - completed

jobs:
  # This job sync this repo to our internal repo
  repo-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Repo Sync
        uses: wei/git-sync@v3
        with:
          source_repo: "nginxinc/kubernetes-ingress"
          source_branch: "master"
          destination_repo: ${{ secrets.SYNC_DEST_REPO_URL }}
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SYNC_SSH_PRIVATE_KEY }}

  # This job open a PR to sync the generated CRD files across to nginx-ingress-operator
  # (see .github/sync.yml for config details)
  crds-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run CRD File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.NGINX_PAT }}
          ASSIGNEES: "nginxinc/kic"
          PR_LABELS: chore
          COMMIT_EACH_FILE: false

  # This job sync the labels across the various repos
  labels-sync:
    strategy:
      # don't break another job if one is failed
      fail-fast: false
      matrix:
        repo:
          - nginxinc/kubernetes-ingress
          - nginxinc/nginx-ingress-operator
          - nginxinc/nginx-prometheus-exporter
          - nginxinc/nginx-plus-go-client
          - nginxinc/nginx-asg-sync
          - nginxinc/nginx-ns1-gslb
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync Labels
        uses: micnncim/action-label-syncer@v1
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.NGINX_PAT }}
          prune: true
