name: Sync

on:
  workflow_run:
    branches: main
    workflows:
      - "CI"
    types:
      - completed

concurrency:
  group: ${{ github.ref_name }}-sync
  cancel-in-progress: true

jobs:
  # This job sync this repo to our internal repo
  repo-sync:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Repo Sync
        uses: wei/git-sync@v3
        with:
          source_repo: "nginxinc/kubernetes-ingress"
          source_branch: "main"
          destination_repo: ${{ secrets.SYNC_DEST_REPO_URL }}
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SYNC_SSH_PRIVATE_KEY }}

  # This job sync the labels across the various repos
  labels-sync:
    strategy:
      # don't break another job if one is failed
      fail-fast: false
      matrix:
        repo:
          - nginxinc/kubernetes-ingress
          - nginxinc/nginx-ingress-helm-operator
          - nginxinc/nginx-prometheus-exporter
          - nginxinc/nginx-plus-go-client
          - nginxinc/nginx-asg-sync
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sync Labels
        uses: micnncim/action-label-syncer@v1
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.NGINX_PAT }}
          prune: true
