name: Update GitHub Release Draft

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Release branch"
        required: true
        type: string

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-release-draft
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  variables:
    name: Set variables
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      chart_version: ${{ steps.vars.outputs.chart_version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Golang Environment
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - name: Set Variables
        id: vars
        run: |
          source .github/data/version.txt
          echo "chart_version=${HELM_CHART_VERSION}" >> $GITHUB_OUTPUT

      - name: Output variables
        run: |
          echo chart_version: ${{ steps.vars.outputs.chart_version }}

  update-release-draft:
    name: Update Release Draft
    runs-on: ubuntu-22.04
    needs: [variables]
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.branch }}

      - name: Create/Update Draft
        uses: lucacome/draft-release@38def8b74645796e9743b53e0f187d4a8915ea3e # v1.2.3
        id: release-notes
        with:
          minor-label: "enhancement"
          major-label: "change"
          publish: false
          collapse-after: 50
          variables: |
            helm-chart=${{ needs.variables.outputs.chart_version }}
          notes-footer: |
            ## Upgrade
            - For NGINX, use the {{version}} images from our [DockerHub](https://hub.docker.com/r/nginx/nginx-ingress/tags?page=1&ordering=last_updated&name={{version-number}}), [GitHub Container](https://github.com/nginx/kubernetes-ingress/pkgs/container/kubernetes-ingress), [Amazon ECR Public Gallery](https://gallery.ecr.aws/nginx/nginx-ingress) or [Quay.io](https://quay.io/repository/nginx/nginx-ingress).
            - For NGINX Plus, use the {{version}} images from the F5 Container registry or build your own image using the {{version}} source code.
            - For Helm, use version {{helm-chart}} of the chart.

            ## Resources
            - Documentation -- https://docs.nginx.com/nginx-ingress-controller/
            - Configuration examples -- https://github.com/nginx/kubernetes-ingress/tree/{{version}}/examples
            - Helm Chart -- https://github.com/nginx/kubernetes-ingress/tree/{{version}}/deployments/helm-chart
            - Operator -- https://github.com/nginx/nginx-ingress-helm-operator
